import { create } from "zustand";

export const invoiceDetailStore = create((set, get) => ({
  categoryWiseSum: [],
  tableData: [],
  operations: [],
  last_update_info: {},
  invoiceType: null,
  metaData: {},
  bounding_box: {},
  loadingMetadata:false,
  bounding_boxes: [],
  highlightAll: false,
  combinedTableCopy: {},
  reCalculateCWiseSum: false,
  added: false,
  history: [],
  combinedTableHistory: [],
  allowModalDragging: true,
  similarLineItems: [],
  showSimilarLineItemsModal: false,
  similarLineItemsRequiredColumns: [],
  setSimilarLineItemsRequiredColumns: (v) =>
    set({ similarLineItemsRequiredColumns: v }),
  last_edited_line_item_columns: [],
  setLastEditedLineItemColumns: (v) =>
    set({ last_edited_line_item_columns: v }),
  setShowSimilarLineItemsModal: (v) => set({ showSimilarLineItemsModal: v }),
  setSimilarLineItems: (v) => set({ similarLineItems: v }),
  setAllowModalDragging: (val) => set({ allowModalDragging: val }),
  stopHovering: true,
  setStopHovering: (v) => set({ stopHovering: v }),
  highlightRow: false,
  prefetchedLinks: {},
  updatedFields: {},
  vendorChanged: false,
  branchChanged: false,
  newVendor: "",
  newBranch: "",
  editBranch: false,
  editVendor: false,
  totalPages: null,
  review_later: false,
  is_unverified_vendor: false,
  is_unverified_branch: false,
  current_document_uuid: null,
  last_edited_line_item: null,
  setLastEditedLineItem: (v) => set({ last_edited_line_item: v }),
  setReviewLater: (val) => set({ review_later: val }),
  setCombinedTableHistory: (history) => set({ combinedTableHistory: history }),
  setTotalPages: (pages) => set({ totalPages: pages }),
  setVendorChanged: (value) => set({ vendorChanged: value }),
  setBranchChanged: (value) => set({ branchChanged: value }),
  setNewVendor: (value) => set({ newVendor: value }),
  setNewBranch: (value) => set({ newBranch: value }),
  setEditBranch: (value) => set({ editBranch: value }),
  setEditVendor: (value) => set({ editVendor: value }),
  isModalOpen: false,
  metadataTableCopy: {},
  warning_checkbox_checked: false,
  setMetadataTableCopy: (cpy) => set({ metadataTableCopy: cpy }),
  setLoadingMetadata:(val)=>set({loadingMetadata:val}),
  showTextExtractionModal: false,
  setShowTextExtractionModal: (val) => set({ showTextExtractionModal: val }),
  setWarningCheckboxChecked: (v) => set({ warning_checkbox_checked: v }),
  setIsModalOpen: (val) => set({ isModalOpen: val }),
  setUpdatedFields: (update) =>
    set((state) => ({
      updatedFields:
        typeof update === "function"
          ? update(state.updatedFields)
          : { ...state.updatedFields, ...update }
    })),
  clearUpdatedFields: () => set({ updatedFields: {} }),
  totalExtendedPrce: 0,
  setTotalExtendedPrice: (val) => set({ totalExtendedPrce: val }),

  setHighlightRow: (val) => set({ highlightRow: val }),
  setPrefetchedLinks: (link) => set({ prefetchedLinks: link }),
  setHistory: (his) => set({ history: his }),
  setReCalculateCWiseSum: (val) => set({ reCalculateCWiseSum: val }),
  setCategoryWiseSum: (sum) => set({ categoryWiseSum: sum }),
  setTableData: (data) => set({ tableData: data }),
  setCombinedTableCopy: (data) => set({ combinedTableCopy: data }),
  setOperations: (data) => set({ operations: data }),
  setLastUpdateInfo: (info) => set({ last_update_info: info }),
  setInvoiceType: (type) => set({ invoiceType: type }),
  setMetaData: (data) => set({ metaData: data }),
  setBoundingBox: (box) => set({ bounding_box: box }),
  setHighlightAll: (highlightAll) => set({ highlightAll: highlightAll }),
  setIsUnverifiedVendor: (v) => set({ is_unverified_vendor: v }),
  setIsUnverifiedBranch: (v) => set({ is_unverified_branch: v }),
  setBoundingBoxes: (boxes) => set({ bounding_boxes: boxes }),
  setCurrentDocumentUUID: (v) => set({ current_document_uuid: v }),
  setAdded: (flag) => set({ added: flag }),
  clearStore: () =>
    set({
      categoryWiseSum: [],
      bounding_box: {},
      tableData: [],
      last_update_info: {},
      operations: [],
      invoiceType: null,
      metaData: {},
      highlightAll: false,
      combinedTableCopy: {},
      vendorChanged: false,
      branchChanged: false,
      newVendor: "",
      newBranch: "",
      editBranch: false,
      editVendor: false,
      showTextExtractionModal: false,
      metadataTableCopy: {},
      is_unverified_vendor: false,
      is_unverified_branch: false,
      current_document_uuid: null,
      warning_checkbox_checked: false,
      stopHovering: true,
      last_edited_line_item: null,
      last_edited_line_item_columns: [],
      similarLineItems: [],
      showSimilarLineItemsModal: false,
      similarLineItemsRequiredColumns: []
    })
}));
